### ISSUE TITLE
Privacy policy link hidden

### ISSUE THREAD

**Issue by iandunn** [wceu/wceu2022#1]
Hi 👋🏻 

WordCamp.org recently [added privacy policy links](https://github.com/WordPress/wordcamp.org/commit/3e129d0eabf6d08f06f7ff07f6adae0bdc975333) to most<sup>[1]</sup> site footers. @ryelle noticed that WCEU is hiding the link in the 2020-2022 sites, and I was curious what the reason for that is?

[It pre-dates the recent addition](https://github.com/wceu/wceu-2020/commit/d380e49f192391993307bc8d95a237ddbb7cf6a7), so maybe the reason for it no longer exists, and the link can be restored?

xref
* https://wordpress.slack.com/archives/C08M59V3P/p1623853580039800

----

[1] - Not all themes support it yet, see https://core.trac.wordpress.org/ticket/53446 and https://core.trac.wordpress.org/ticket/53445

**Comment by robertotunon** [comment]
Solved on this commit: https://github.com/wceu/wceu2022/commit/79a4daaaa544c9a7a3ffc9c3c8edef1a37f563f9

**Comment by iandunn** [comment]
Thanks!
